apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.familytree365.com
      http:
        paths:
          - backend:
              serviceName: backend
              servicePort: 80
