version: '3.5'
services:
  php:
    image: familytree365/backend:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - APP_KEY="base64:Yh1Bw3m1Tj7eyPFbCyUUg6q0Znct8Em0YpsxACWPVx0="
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
